baseURL = 'https://lawtext.github.io/regulations'
title = 'ä¸­å›½æ³•å¾‹æ³•è§„åœ¨çº¿æ–‡åº“ï¼ˆåœ°æ–¹æ³•è§„ï¼‰'

# è¯­è¨€è®¾ç½®
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true
# enableEmoji = true
contentDir = "content/"
enableMissingTranslationPlaceholders = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo = true

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"
# disableKinds = ["RSS"]
# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy"]

# hugo module configuration
[module]
[module.hugoVersion]
extended = true
min = "0.146.0"
[[module.imports]]
path = "github.com/google/docsy"
disable = false

# You can add your own taxonomies
# [taxonomies]
# tag = "tags"
# category = "categories"
# year = "years"
# keyword = "keywords"

# Configure how URLs look like per section.
# [permalinks]
# blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "Smart"

# Language configuration

# [languages]
# [languages.en]
# languageName ="English"
# title = "Goldydocs"
# contentDir = "content/fa"
# languageDirection = "rtl"
# [languages.en.params]
# description = "A Docsy example site"
# time_format_default = "2006.01.02"
# time_format_blog = "2006.01.02"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.extensions]
[markup.goldmark.extensions.cjk]
eastAsianLineBreaks = true
eastAsianLineBreaksStyle = 'simple'
enable = true
escapedSpace = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [ [ "\\[", "\\]" ], [ "$$", "$$" ] ]
inline = [ [ "\\(", "\\)" ] ]

[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "tango"
# guessSyntax = true

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
home = ['HTML']
page = ['HTML']
section = ["HTML"]

# Everything below this are Site Params
[params]
reading_speed = 400

# privacy_policy = "https://policies.google.com/privacy"
# Enable syntax highlighting and copy buttons on code blocks with Prism
# prism_syntax_highlighting = true

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]
# version_menu = "Releases"
# archived_version = false
# version = "0.7.1"
# url_latest_version = "https://example.com"

# # Repository configuration (URLs for in-page links to opening issues and suggesting changes)
# github_repo = "https://github.com/google/docsy-example"
# github_project_repo = "https://github.com/google/docsy"
# github_subdir = ""
# github_branch= "main"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = ""

# Enable Lunr.js offline search
# offlineSearch = true
# offlineSearchSummaryLength = 200
# offlineSearchMaxResults = 25
# [params.search.algolia]


[params.copyright]
authors = "å»ºç«™ [Hugo](https://gohugo.io/) | ä¸»é¢˜ [Docsy](https://www.docsy.dev/)"
from_year = 2026
to_year = "present"


# User interface configuration
[params.ui]
# breadcrumb_disable = false
# footer_about_enable = false
# navbar_logo = true
# navbar_translucent_over_cover_disable = false
showLightDarkModeMenu = true
sidebar_cache_limit = 1000
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_menu_truncate=2000
sidebar_search_disable = false
ul_show = 1

[params.ui.feedback]
enable = true
yes = 'æ„Ÿè°¢æ”¯æŒï¼Œå¦‚æœ‰æ–°éœ€æ±‚è¯·è®¿é—® ğŸ”—<a href="https://github.com/lawtext/regulations/issues/new">æäº¤Issue</a>ã€‚'
no = 'å¾ˆé—æ†¾ï¼Œå¦‚æœ‰é—®é¢˜è¯·è®¿é—® ğŸ”—<a href="https://github.com/lawtext/regulations/issues/new">æäº¤Issue</a>ã€‚'

[params.ui.readingtime]
enable = true

[params.page]
pageSize = 100 # listé¡µé¢æ¯é¡µé¡¹æ•°

[menu]
[[menu.main]]
    name = 'ä¸»é¡µ'
    pageRef = '/'
    weight = 10
    pre = '<i class="fa-regular fa-house"></i>'

[[menu.main]]
    name = 'ååŒ—'
    weight = 20
    pre = '<i class="mi mi-diqu-huabei"></i>'

[[menu.main]]
    name = 'ä¸œåŒ—'
    weight = 30
    pre = '<i class="mi mi-diqu-dongbei"></i>'

[[menu.main]]
    name = 'åä¸œ'
    weight = 40
    pre = '<i class="mi mi-diqu-huadong"></i>'

[[menu.main]]
    name = 'åä¸­'
    weight = 50
    pre = '<i class="mi mi-diqu-huazhong"></i>'

[[menu.main]]
    name = 'åå—'
    weight = 55
    pre = '<i class="mi mi-diqu-huanan"></i>'


[[menu.main]]
    name = 'è¥¿å—'
    weight = 60
    pre = '<i class="mi mi-diqu-xinan"></i>'

[[menu.main]]
    name = 'è¥¿åŒ—'
    weight = 70
    pre = '<i class="mi mi-diqu-xibei"></i>'

[[menu.main]]
    name = 'å…¨å›½æ³•å¾‹'
    weight = 90
    url = 'https://lawtext.github.io/'
    pre = '<i class="mi mi-cn1"></i>'

# [services]
# [services.disqus]
# shortname = ''
