name: GitHub Pages

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".gitignore"
  workflow_dispatch:
  schedule:
    - cron: "5 12 15 * *"

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    env:
      USER: ${{ github.repository_owner }}
      REPO: ${{ github.event.repository.name }}
      CODE: ${{ secrets.REPO }}
      DATA: ${{ secrets.DATA }}
      SRC_NAME: source
      DATA_NAME: data
      HUGO_VERSION: latest
      HUGO_ENVIRONMENT: production

    steps:
      - uses: actions/checkout@v4

      - name: Checkout src repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USER }}/${{ env.CODE }}
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ env.SRC_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Checkout data repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.USER }}/${{ env.DATA }}
          token: ${{ secrets.GH_TOKEN }}
          path: ${{ env.DATA_NAME }}
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Run format markdown
        run: |
          pushd ${SRC_NAME} && 
          bash scripts/process-format2.sh ${DATA_NAME} content -1 &&
          popd

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update
          # commit_options: '--no-verify --signoff'
          # push_options: "--force"
          file_pattern: "content"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Setup Node
        uses: pnpm/action-setup@v4

      - run: pnpm install
      - run: hugo mod tidy

      - name: Build Site
        run: |
          hugo --enableGitInfo --gc --minify --baseURL https://${USER}.github.io/${REPO}

      - name: Setup pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

      - name: Deploy to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
